# Environment name.
name: neoantigen-nf

# Conda channels where to pull packages from.
channels:
  - conda-forge
  - bioconda
  - r
  - nodefaults # Do not look for packages in the default conda channel!

# User-defined dependencies of the environment.  
dependencies:
  - conda-forge::python=3.11.2
  - bioconda::optitype=1.3.5
  - conda-forge::pip=23.3.1
  - conda-forge::numpy=1.26.4
  - conda-forge::pyomo=6.7.3
  - bioconda::pysam=0.22.1
  - conda-forge::matplotlib=3.9.1
  - conda-forge::pytables=3.9.2
  - conda-forge::pandas=2.2.2
  - conda-forge::future=1.0.0
  - conda-forge::hdf5=1.14.3
  - bioconda::razers3=3.5.8
  - conda-forge::glpk=5.0
  - conda-forge::r-base=4.3.3
  - conda-forge::r-biocmanager=1.30.23
  - conda-forge::r-devtools=2.4.5
  - conda-forge::r-optparse=1.7.5
  - bioconda::bioconductor-ensemblvep=1.44.0
  - bioconda::mhcflurry=2.1.2
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-readr=2.1.5
  - conda-forge::r-tidyr=1.3.1
  - conda-forge::r-ggplot2=3.5.1
  - bioconda::bcftools=1.20
  - bioconda::samtools
  - bioconda::bioconductor-biomart=2.58.0

# To update the env:
# conda env update --name neoantigen-nf --file conda.yml --prune        